items:
- name: Документация по Ansible в Azure
  href: ./index.yml
- name: Обзор
  items:
  - name: Общие сведения об Ansible в Azure
    href: ./ansible-overview.md
- name: Быстрое начало работы
  items:
  - name: Установка Ansible на виртуальной машине Linux
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Создание виртуальной машины Linux
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Управление виртуальной машиной Linux
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  - name: Запуск playbook в Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
  expanded: true
- name: Учебники
  items:
  - name: AKS
    items:
    - name: Создание и настройка кластеров AKS
      href: ./ansible-create-configure-aks.md
  - name: Служба приложений
    items:
    - name: Создание и настройка веб-приложений Azure
      href: ./ansible-create-configure-azure-web-apps.md
    - name: Масштабирование веб-приложений Azure
      href: ./ansible-scale-azure-web-apps.md
  - name: Шлюз приложений
    items:
    - name: Создание и настройка Шлюза приложений Azure
      href: ./ansible-create-configure-application-gateway.md
  - name: Базы данных
    items:
    - name: Создание и настройка базы данных Azure для MySQL
      href: ./ansible-create-configure-mysql.md
  - name: Динамический список
    items:
    - name: Управление динамическими списками
      href: ./ansible-manage-azure-dynamic-inventories.md
  - name: Виртуальная сеть
    items:
    - name: Создание и настройка таблиц маршрутов
      href: ./ansible-create-configure-route-table.md
  - name: Масштабируемый набор виртуальных машин
    items:
    - name: Создание и настройка VMSS
      href: ./ansible-create-configure-vmss.md
    - name: Развертывание приложения в VMSS
      href: ./ansible-deploy-app-vmss.md
    - name: Автомасштабирование VMSS
      href: ./ansible-auto-scale-vmss.md
- name: Справочные материалы
  items:
  - name: Роли Playbook
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Выпуски и компоненты
    href: ./ansible-matrix.md
  - name: Экземпляры контейнеров Azure
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Функции Azure
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Балансировщики нагрузки
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Виртуальные машины
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Все модули для Azure
    href: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Средства
  items:
  - name: Расширение Visual Studio Code для Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: 914987ee58a2ba09295d425c2107ba7eb192c131
ms.sourcegitcommit: a408b0e5551893e485fa78cd7aa91956197b5018
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 01/17/2019
ms.locfileid: "54359244"
