items:
- name: Ansible в Azure
  href: ./index.yml
- name: Обзор
  items:
  - name: Общие сведения об Ansible в Azure
    href: ./ansible-overview.md
- name: Быстрое начало работы
  items:
  - name: Установка Ansible на виртуальной машине Linux
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Создание виртуальной машины Linux
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Управление виртуальной машиной Linux
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  expanded: true
- name: Учебники
  items:
  - name: Запуск playbook в Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Управление динамическими списками
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
  - name: Создание и настройка VMSS
    href: ./ansible-create-configure-vmss.md
  - name: Развертывание приложения в VMSS
    href: ./ansible-deploy-app-vmss.md
  - name: Создание и настройка кластеров AKS
    href: ./ansible-create-configure-aks.md
- name: Справочные материалы
  items:
  - name: Роли Playbook
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Выпуски и компоненты
    href: ./ansible-matrix.md
  - name: Экземпляры контейнеров Azure
    href: http://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Функции Azure
    href: http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Балансировщики нагрузки
    href: http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Виртуальные машины
    href: http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Все модули для Azure
    href: http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Средства
  items:
  - name: Расширение Visual Studio Code для Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: 8f803114e966a3b544e4a4788752be8c494ad33a
ms.sourcegitcommit: 76797c962fa04d8af9a7b9153eaa042cf74b2699
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 08/21/2018
ms.locfileid: "41927960"
